backend:
  name: {{ site.Params.admin.git | default "git-gateway" }}
  branch: {{ site.Params.admin.branch | default "master" }}
display_url: "{{ site.BaseURL }}"
{{ if site.Params.admin.i18n.locales }}
i18n:
  structure: multiple_files
  locales: {{ site.Params.admin.i18n.locales }}
  default_locale: {{ site.Params.admin.i18n.default_locale }}
{{ end }}
local_backend: true
locale: {{ site.Params.admin.locale }}
logo_url: "./logo.svg"
media_folder: "static/uploads"
public_folder: "/uploads"
publish_mode: {{ site.Params.admin.publish_mode | default "simple"  }}
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

{{ partialCached "admin/collections/index.yml" . }}
