{{- $subfields := slice "label" "value" "color" -}} 
{{- $items := dict "items" (dict "name" "chart" "fields" $subfields) -}}
{{- $fields := slice 
  "title" 
  "chart_type" 
  $items
  "chart_data"  -}}
{{- $fields = partial "admin/func/GetFields.html" (dict "field" . "fields" $fields) -}}

{{- $args := dict 
  "label" (i18n "admin.fields.chart.label")
  "name" "chart"
  "fields" $fields
  -}}

{{ partial "admin/widgets/object.js" $args }}
