{{ $nested := (index site.Params.admin.collections .).nested | default site.Params.admin.nested.depth }}
{{ if gt $nested 1 }}
nested: {
  depth: {{ $nested }},
},
{{ partialCached "admin/cms/decapcms/collection/config/parent.yml" }}
{{ end }}