{{- $partial := partial "admin/cms/pagescms/config.yml" . -}}

{{- $sliceCompatibity := slice 
  (dict "{{slug}}/_index" "{fields.title}/_index.md")
  (dict "{{slug}}" "{fields.title}.md")
  (dict "{{year}}" "{year}") 
  (dict "{{month}}" "{month}") 
  (dict "{{day}}" "{day}") 
  (dict "path:" "filename:") 
  (dict "folder:" "type: 'collection', path:") 
  (dict "widget: 'hidden'" "widget: 'boolean', hidden: true") 
  (dict "widget: 'list'" "widget: 'object', list: true") 
  (dict "widget: 'datetime'" "widget: 'date'") 
  (dict "widget: 'markdown'" "widget: 'rich-text'") 
  (dict "widget:" "type:") 
  (dict "collections:" "content:") 
  -}}

{{- range $sliceCompatibity }}
  {{- range $key, $value := . }}
    {{- $partial = replace $partial $key $value }}
  {{- end }}
{{- end }}

{{ transform.Remarshal "yaml" $partial }}
