{
  name: products_categories,
  folder: content/products_categories,
  label: {{ i18n "admin.collections.products_categories.label" }},
  label_singular: {{ i18n "admin.collections.products_categories.label" 1 }},
  description: {{ i18n "admin.collections.products_categories._description" }},
  
  create: true,
  editor: { preview: {{ site.Params.admin.preview }} },
  i18n: true,

  path: '{{`{{slug}}`}}',
  slug: '{{`{{slug}}/_index`}}',
  sortable_fields: ['title'],

  filter: { field: 'isIndex', value: false },

  fields: [
    {{ partialCached "admin/collections/fields.terms.default.yml" . }}
  ]
}