{
  name: 'products_tags',
  folder: 'content/products_tags',
  label: '{{ i18n "admin.collections.products_tags.label" }}',
  label_singular: '{{ i18n "admin.collections.products_tags.label" 1 }}',
  description: '{{ i18n "admin.collections.products_tags._description" }}',
  
  create: {{ site.Params.admin.collections.products_tags.create | default true }},
  editor: { preview: {{ site.Params.admin.preview | default false }} },
  i18n: true,

  path: '{{`{{slug}}/_index`}}',
  {{ partial "admin/collections/config/slug.yml" }}

  {{ partial "admin/collections/types/_default.yml" . }}
}