{
  name: products,
  folder: content/products,
  label: {{ i18n "admin.collections.products.label" }},
  label_singular: {{ i18n "admin.collections.products.label" 1 }},
  description: {{ i18n "admin.collections.products._description" }},
  
  create: true,
  editor: { preview: {{ site.Params.admin.preview }} },
  i18n: true,

  path: '{{`{{year}}/{{slug}}`}}',
  {{ partial "admin/collections/config/slug.yml" }}
  
  {{ partial "admin/collections/config/icon.yml" "box" }}
  {{ partial "admin/collections/config/filter.yml" }}
  {{ partial "admin/collections/config/sortable.yml" }}

  {{ partial "admin/collections/fields.yml" (dict "collection" "products") }}
}