{
  name: 'products_categories',
  folder: 'content/products_categories',
  label: '{{ i18n "admin.collections.products_categories.label" }}',
  label_singular: '{{ i18n "admin.collections.products_categories.label" 1 }}',
  description: '{{ i18n "admin.collections.products_categories._description" }}',
  
  create: {{ site.Params.admin.collections.products_categories.create | default true }},
  editor: { preview: {{ site.Params.admin.preview | default false }} },
  i18n: true,

  path: '{{`{{slug}}/_index`}}',
  {{ partial "admin/collections/config/slug.yml" }}

  {{ partial "admin/collections/types/_default.yml" . }}
}