{
  name: 'products_tags',
  folder: 'content/products_tags',
  label: '{{ i18n "admin.collections.products_tags.label" }}',
  label_singular: '{{ i18n "admin.collections.products_tags.label" 1 }}',
  description: '{{ i18n "admin.collections.products_tags._description" }}',
  i18n: true,
  {{ partial "admin/collections/config/create.yml" . }}
  {{ partial "admin/collections/config/preview.yml" . }}
  {{ partial "admin/collections/config/path.yml" . }}
  {{ partial "admin/collections/config/slug.yml" . }}

  {{ partial "admin/collections/types/_default.html" . }}
}