{
  name: products,
  folder: content/products,
  label: '{{ i18n "admin.collections.products.label" }}',
  label_singular: '{{ i18n "admin.collections.products.label" 1 }}',
  description: '{{ i18n "admin.collections.products._description" }}',
  
  create: {{ site.Params.admin.collections.products.create | default true }},
  editor: { preview: {{ site.Params.admin.preview | default false }} },
  i18n: true,

  path: '{{`{{year}}/{{slug}}`}}',
  media_folder: {{ site.Params.admin.media.media_folder | default "/assets/images/uploads" }},
  public_folder: {{ site.Params.admin.media.public_folder | default "/images/uploads" }},
  {{ partial "admin/collections/config/slug.yml" }}
  
  {{ partial "admin/collections/types/_default.yml" . }}
}