{
  name: products_tags,
  folder: content/products_tags,
  label: {{ i18n "admin.collections.products_tags.label" }},
  label_singular: {{ i18n "admin.collections.products_tags.label" 1 }},
  description: {{ i18n "admin.collections.products_tags._description" }},
  
  create: true,
  editor: { preview: {{ site.Params.admin.preview }} },
  i18n: true,

  path: '{{`{{slug}}/_index`}}',
  slug: '{{`{{slug}}`}}',
  nested: { depth: 2 },

  {{ partial "admin/collections/config/icon.yml" "bookmarks" }}
  {{ partial "admin/collections/config/filter.yml" }}
  {{ partial "admin/collections/config/sortable.yml" }}

  {{ partialCached "admin/collections/fields.terms.default.yml" . }}
}