{
  name: products,
  folder: content/products,
  label: {{ i18n "admin.collections.products.label" }},
  label_singular: {{ i18n "admin.collections.products.label" 1 }},
  description: {{ i18n "admin.collections.products._description" }},
  
  create: true,
  editor: { preview: {{ site.Params.admin.preview }} },
  i18n: true,

  path: '{{`{{year}}/{{slug}}`}}',
  slug: '{{`{{slug}}`}}',
  sortable_fields: ['title'],

  filter: { field: 'isIndex', value: false },

  fields: [
    {{ partialCached "admin/collections/fields.yml" (dict "collection" "products") }}
  ]
}