backend:
  branch: {{ site.Params.admin.branch | default "main" }}
  name: {{ site.Params.admin.git | default "git-gateway" }}
  {{- with site.Params.admin.repo }}
  repo: {{ . }}
  {{- end }}
  {{- with site.Params.admin.base_url }}
  base_url: {{ . }}
  {{- end }}
  {{- with site.Params.admin.auth_endpoint }}
  auth_endpoint: {{ . }}
  {{- end }}

display_url: "{{ site.BaseURL }}"

{{- if site.Params.admin.i18n.locales }}
i18n:
  structure: multiple_files
  locales: {{ site.Params.admin.i18n.locales }}
  default_locale: {{ site.Params.admin.i18n.default_locale }}
{{- end }}

local_backend: true
locale: {{ site.Params.admin.locale | default (index site.Languages 0) | default "en" }}
logo: 
  src: "./logo.svg"
  show_in_header: true
media_folder: {{ site.Params.admin.media.media_folder | default "assets/images/uploads" }}

{{- with site.Params.admin.media.cloud }}
media_library:
  name: "{{ .name }}"
  config:
    {{- with .cloud_name }}
    cloud_name: "{{ . }}"
    {{ end }}
    {{- with .api_key }}
    api_key: {{ . }}
    {{ end }}
    {{- with .public_key }}
    publicKey: {{ . }}
    {{ end }}
    {{- with .tabs }}
    tabs: {{ . }}
    {{ end }}
{{- end }}

public_folder: {{ site.Params.admin.media.public_folder | default "/images/uploads" }}
publish_mode: {{ site.Params.admin.publish_mode | default "simple" }}
slug:
  encoding: "unicode"
  clean_accents: false
  sanitize_replacement: "-"

{{ transform.Remarshal "yaml" (partial "admin/collections/index.yml" .) }}
