backend:
  branch: {{ site.Params.admin.branch | default "main" }}
  name: {{ site.Params.admin.git | default "git-gateway" }}
  {{ with site.Params.admin.repo }}
  repo: "{{ . }}"
  {{ end }}

display_url: "{{ site.BaseURL }}"

{{ if site.Params.admin.i18n.locales }}
i18n:
  structure: multiple_files
  locales: {{ site.Params.admin.i18n.locales }}
  default_locale: {{ site.Params.admin.i18n.default_locale }}
{{ end }}

local_backend: true
locale: {{ index site.Languages 0 | default "en" }}
logo_url: "./logo.svg"
media_folder: "static/uploads"

{{ with site.Params.admin.media.cloud }}
media_library:
  name: "{{ .name }}"
  config:
    {{ with .cloud_name }}
    cloud_name: "{{ . }}"
    {{ end }}
    {{ with .api_key }}
    api_key: {{ . }}
    {{ end }}
    {{ with .public_key }}
    publicKey: {{ . }}
    {{ end }}
{{ end }}

public_folder: "/uploads"
publish_mode: {{ site.Params.admin.publish_mode | default "simple"  }}
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

{{ partialCached "admin/collections/index.yml" . }}
