{{- $cms := site.Params.admin.cms | default "decapcms" -}}
{{- $file := print "admin/cms/" $cms "/collection/config/filter.yml" -}}
{{- if templates.Exists ( printf "partials/%s" $file ) -}}
  {{- $args := . -}}
  {{- if not $args -}}
    {{- $args = dict "field" "isIndex" "value" false -}}
  {{- end -}}
  {{ partial $file $args }}
{{- end -}}